### ISSUE TITLE
If totalItems is undefined, do not display "of X" and do not display >> control

### ISSUE THREAD

**Issue by psbanka** [ciena-frost/ember-frost-list#109]
Some APIs do not provide the total number of records and have no way to go to the end of the record-set (e.g. Cassandra-based APIs). If the user passes in `undefined` for `totalItems`, remove these from the UI.

**Comment by sglanzer-fire** [comment]
The convention for unidirectional APIs is to use infinite scroll with onLoadNext.  Visible pagination controls were provided as a backwards compatibility feature and should not be considered the desired mechanism for handling paging.

@psbanka I sent you an email regarding this approximately a week and a half ago, please message me if you need to discuss.

**Comment by sglanzer-fire** [comment]
No intent to support unidirectional paging using visible pagination controls.
