### ISSUE TITLE
Remove reference comparisons for items and enforce user set itemKeys

### ISSUE THREAD

**Issue by frosetti** [ciena-frost/ember-frost-list#117]
itemKey will guarantee uniqueness of items selectedItems and expandedItems

I suggest taking it further and making selectedItems/expandedItems a map.
By doing this removal of items from selectedItems and expandedItems could be a faster process.
It would make for easier/faster logic in basic/specific/range clicks.

**Comment by sglanzer-fire** [comment]
Agreed on `itemKey` being the standard in the next #major#

Not sure if I buy the value of the map in this case (due to ordering being a primarily consideration), but we'll consider it

**Comment by frosetti** [comment]
The only counter argument I can give is if you guarantee an item key, why would you want to store something in a list.
When are you expecting selectedItems 'order' to be of any use? 
Remove the last 3 items you pushed? We can't use pushObject due to it will add duplicates.
addObjects will push to the end (I think) or not at all if it already exists, which means you lost ordering again.
