### ISSUE TITLE
Would be nice if ember-frost-list worked with EmberData objects as the selected items

### ISSUE THREAD

**Issue by psbanka** [ciena-frost/ember-frost-list#129]
This mostly works except for range-selection. Range-selection fails because an Ember Data object doesn't have a `findIndex()` method. 

https://cl.ly/2M2y0h2b1D3h

If `ember-frost-list` used a different method here, it might be possible to simply pass Ember Data objects directly. Instead, a dev has to do a `selectedObjects.map((item) => item.toJSON({includeId: true})` to convert the objects to POJOs.

**Comment by psbanka** [comment]
expandAll is also broken when passing Ember Data objects, FWIW.

**Comment by sglanzer-fire** [comment]
Matt and I were discussing wrapping the items with a state container, seems like an appropriate time to move on that - 2 birds with one stone - I'll give it a shot today
