### ISSUE TITLE
Add single-select and always expanded options

### ISSUE THREAD

**Issue by twjohnston** [ciena-frost/ember-frost-list#185]
# FEATURE REQUEST / CODE CHANGE

## Summary
Two new optional parameters are being proposed to add the following functionality to `frost-list`: limiting a list to be single-select only, and forcing all items to be always expanded.

## Motivation
UX changes to existing components would be easily facilitated by these new features, and there is at least one instance of an existing component already forcing single-select behavior on its `frost-list`.

The always expanded option saves users clicks in the case where they will want to see all details anyway, but retains the visual distinction between the item title and its expanded content.

## Detailed design
The `singleSelection` parameter, when `true`, will:
- Display `frost-radio-button` instead of `frost-checkbox` in the `frost-list-item-selection` component
- Treat all clicks as if they were `basic`, which will disable the shift-click and ctrl/cmd-click behaviors

The `alwaysExpanded` parameter, when `true`, will:
- Hide the `frost-list-expansion` and `frost-list-item-expansion` components as they will be irrelevant
- Set all items to have their `states.isExpanded` be true

## How we teach this

The single select functionality is reinforced by showing radio buttons instead of checkboxes, and will be included in the dummy app.

The always expanded behavior is fairly self explanatory.

## Drawbacks

Ideally none, since these are optional parameters with defaults set to preserve the existing behavior.

## Alternatives

There is potentially some crossover with`frost-radio-group` for the single-selection behavior, though adding it to `frost-list` retains all the styling of the list for consistency and comes with the expandable item functionality.

**Comment by notmessenger** [comment]
(in the "Motivation" section)
> The always expanded option saves users clicks

What do you mean by the user clicks will be saved?  Are they going to be replayed after some other action or managed via `ember-concurrency`?  Or are you meaning that they will be trapped/discarded/ignored?

**Comment by notmessenger** [comment]
Is there any currently-known need for a list to limit the selection of its content to an arbitrary number of items?  Right now you can select as many as you want (via checkboxes) and this proposes supporting the limiting selection to a single item (via radio buttons) but what about limiting it to 5 items? Or 3? Or 19?

If there is a need for an arbitrary selection amount then a mechanism for indicating this value and a UX to support this would be preferred, as restricting selection to a single item could be implemented via the same mechanism and provide visual continuity between the implementations.

**Comment by notmessenger** [comment]
Do we anticipate in the future supporting the ability to designate that the items should be displayed expanded by default but still be able to be collapsed?  If so then the ability to support this as well as to indicate that items should always remain expanded should be managed via the same single property.

**Comment by twjohnston** [comment]
By "saves users clicks" I just meant it will reduce the number of clicks a user would perform... maybe could have worded that better.

As far as I know, there is no need to support arbitrary selection limits at this time.

I think the ability to support expansion by default but still allowing collapse would be useful, however, so I'll look at adding that.

**Comment by notmessenger** [comment]
> I think the ability to support expansion by default but still allowing collapse would be useful, however, so I'll look at adding that.

You don't have to add the actual support for it, just plan on it being a thing when you are implementing the current behavior.
