### ISSUE TITLE
fix issue with weird extra column at the end?

### ISSUE THREAD

**Issue by rox163** [ciena-frost/ember-frost-list#23]

**Comment by sandersky** [comment]
This has to do with `perfect-scrollbar` being introduced into `ember-frost-core`.

**Comment by vesper2000** [comment]
@sandersky Any chance we can get some help to fix this?

**Comment by sandersky** [comment]
@vesper2000 you mean https://github.com/ciena-frost/ember-frost-list/pull/24 :wink:

**Comment by vesper2000** [comment]
Yeah :)  Always ahead - thanks!
