### ISSUE TITLE
Default value for `defaultHeight` should be null?

### ISSUE THREAD

**Issue by TheOtherDude** [ciena-frost/ember-frost-list#62]
The current default of 45px seems a little random. Any reason we shouldn't set it to null so that the vertical items inherit the height of the list items?

**Comment by sglanzer-fire** [comment]
Agreed, we're also expecting that expansion won't hit a strict default height, so it's better to not assume a height

**Comment by TheOtherDude** [comment]
Unfortunately, `defaultHeight=null` messes up the scrolling.
