### ISSUE TITLE
Implement mechanism for overflow/linewrapping

### ISSUE THREAD

**Issue by Samadroberts** [ciena-frost/ember-frost-list#9]
- BPSO-9353

**Comment by NickLewanowicz** [comment]
<img width="643" alt="screen shot 2017-09-05 at 2 10 05 pm" src="https://user-images.githubusercontent.com/15663269/30075600-3cdcc2dc-9244-11e7-888f-d4fe10100d89.png">
This is the spec that was provided to me for our overflow text
