### ISSUE TITLE
UA parser not getting installed

### ISSUE THREAD

**Issue by TheOtherDude** [ciena-frost/ember-frost-list#95]
I'm getting window.UAParser is not a constructor when I try to select an item. 

The work around is to manually `npm install ua-parser-js` into my project.

**Comment by sglanzer-fire** [comment]
@TheOtherDude It's actually included in the vendor minified currently https://github.com/ciena-frost/ember-frost-list/blob/master/vendor/ua-parser.min.js and pulled in via the build https://github.com/ciena-frost/ember-frost-list/blob/master/index.js#L20 so I'm not sure why it wouldn't be present for you, I haven't seen this issue in the two projects we've upgraded

**Comment by TheOtherDude** [comment]
@sglanzer I must have not rebuilt my project. It's working now.

Thanks!
