### ISSUE TITLE
Create an async test helper that ties to rendered state of list items

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-list#96]
When items are being rendered in a `frost-list` there is (can be) a delay in their rendering.  In an acceptance test this delay causes problems because when attempting to use the hooks to get a count of these items, for example, they are not yet rendered and the test will fail.

An async test helper should be created and exported as part of of this repo that will resolve its promise when all of the list items have been rendered in the current view port.

**Comment by sglanzer-fire** [comment]
Given occlusion (not rendering items that aren't in the viewport) you won't ever be able to use the DOM to verify the correct number of items being rendered.   I'm not sure what the goal of this is precisely, but maybe another approach needs to be explored.

**Comment by notmessenger** [comment]
If anyone has a similar need in the future reach out to me because I have a few ideas on how could possibly approach this, however in the meantime the scenario that initiated this request has changed no longer requiring this to be pursued.
